### PR TITLE
Fixed publication of iOS artifact

### PR DESCRIPTION
**Pull request by Alex009**
We see that ios arm64 not published to maven. So we fix setup of lib (add symlink to enable support of both source sets of iOS without code duplication).
Also in request added RSSI passing to common code (on iOS).
Also commencted signing cause blocks us.

i create request as DRAFT (commented signing and not completed RSSI on android not allow to merge), may be useful for others

### CODE REVIEW

**Comment by Reedyuk** [comment]
Hi, can you resolve the conflict and set the branch ready for merge. I will merge in and setup a new branch to get working for android

**Comment by Reedyuk** [comment]
Hi, i have the fixes locally, but i cannot push, can you give me write access to your fork please.

**Comment by Reedyuk** [comment]
nevermind i have pushed it to my repo via a new branch.

**Comment by Alex009** [comment]
@Reedyuk are you republish library to maven? on maven central i not see update https://mvnrepository.com/artifact/dev.bluefalcon

**Comment by Reedyuk** [comment]
strange, i thought i had released it this morning but apparently not. I will have to check later.

**Comment by Reedyuk** [comment]
it takes a while to appear in mvn repository, check here:
https://search.maven.org/search?q=g:dev.bluefalcon

**Pull request closed without merging**
