### PR TITLE
Ios scan fix

### PR DESCRIPTION
**Pull request by shelaranton**
Fixed BT devices search on iOS (we need to wait BT power on state before performing scan).

### CODE REVIEW

**Comment by Reedyuk** [comment]
@shelaranton - i have added these changes, can you do it this way instead.
https://github.com/Reedyuk/blue-falcon/commit/60194d2d87764ad7b26c3717afbe58a690076d19
If this is ok, i will decline this pull request.

**Comment by shelaranton** [comment]
It's not a good idea to make delay. We don't know how long BT power will
become on.

чт, 31 окт. 2019 г. в 05:13, Andrew Reed <notifications@github.com>:

**Comment by shelaranton** [comment]
Why every second?

чт, 31 окт. 2019 г. в 14:29, Andrew Reed <notifications@github.com>:

**Comment by Reedyuk** [comment]
I could make it a variable maybe.
Let me have a think on the best way to revisit, the delay was used because this then accommodates for all platforms.
Generally we are waiting for iOS to initialise Bluetooth, android it’s usually on.

The common code throws an exception, it is up to the client to do what it needs to do with the exception.
I think it’s the responsibility of the client code to handle the exception.

Sent from my iPhone

On 31 Oct 2019, at 07:58, shelaranton <notifications@github.com> wrote:

﻿Why every second?

чт, 31 окт. 2019 г. в 14:29, Andrew Reed <notifications@github.com>:

**Pull request closed without merging**
